services:
  - type: web
    name: ramzas-chillas  # This will be your new service name
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python start_server.py"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://your_db_user:your_db_password@your_db_host:5432/your_db_name"  # This will be your new database URL
      - key: SECRET_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 4